DEBUG - 2025-04-21 21:11:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-04-21 21:12:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-04-21 21:12:05 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/logo.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'logo.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:05 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/logo-mini.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'logo-mini.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:06 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/faces/face4.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face4.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:06 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/faces/face2.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face2.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:06 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/faces/face3.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face3.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:06 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 49
[Method: GET, Route: admin/usuarios/show/images/faces/face5.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(49): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->show('images', 'faces', 'face5.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
DEBUG - 2025-04-21 21:12:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-04-21 21:12:08 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/logo.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'logo.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:08 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/logo-mini.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'logo-mini.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:08 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face4.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face4.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:09 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face2.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face2.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:09 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face3.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face3.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:09 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face5.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face5.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
INFO - 2025-04-21 21:12:24 --> CSRF token verified.
ERROR - 2025-04-21 21:12:24 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\food\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\food\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\food\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\food\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\food\system\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
#8 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\xampp\htdocs\food\system\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
#10 C:\xampp\htdocs\food\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#11 C:\xampp\htdocs\food\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\food\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\food\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\food\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\food\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-04-21 21:12:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: admin/usuarios/atualizar/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 6 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'12345678\', `password_confirmation` = \'12345678\', `updated_at` = \'2025-04-21 21:12:24\'
WHERE `usuarios`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'12345678\', `password_confirmation` = \'12345678\', `updated_at` = \'2025-04-21 21:12:24\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 8 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:12:24 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'12345678\', `password_confirmation` = \'12345678\', `updated_at` = \'2025-04-21 21:12:24\'
WHERE `usuarios`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'12345678\', `password_confirmation` = \'12345678\', `updated_at` = \'2025-04-21 21:12:24\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'12345678\', `password_confirmation` = \'12345678\', `updated_at` = \'2025-04-21 21:12:24\'
WHERE `usuarios`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 9 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
DEBUG - 2025-04-21 21:15:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-04-21 21:15:03 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/logo.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'logo.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:03 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/logo-mini.svg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'logo-mini.svg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:04 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face4.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face4.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:04 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face2.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face2.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:04 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face3.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face3.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:04 --> TypeError: App\Controllers\Admin\Usuarios::buscaUsuarioOu404(): Argument #1 ($id) must be of type ?int, string given, called in C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php on line 64
[Method: GET, Route: admin/usuarios/editar/images/faces/face5.jpg]
in APPPATH\Controllers\Admin\Usuarios.php on line 116.
 1 APPPATH\Controllers\Admin\Usuarios.php(64): App\Controllers\Admin\Usuarios->buscaUsuarioOu404('images')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->editar('images', 'faces', 'face5.jpg')
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
INFO - 2025-04-21 21:15:16 --> CSRF token verified.
ERROR - 2025-04-21 21:15:16 --> mysqli_sql_exception: Unknown column 'password_confirmation' in 'field list' in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\food\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\food\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\food\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\food\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\food\system\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
#8 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\xampp\htdocs\food\system\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
#10 C:\xampp\htdocs\food\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#11 C:\xampp\htdocs\food\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\food\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\food\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\food\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\food\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-04-21 21:15:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_confirmation' in 'field list'
[Method: POST, Route: admin/usuarios/atualizar/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 6 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_confirmation' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:15:16\'
WHERE `usuarios`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:15:16\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 8 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:15:16 --> [Caused by] mysqli_sql_exception: Unknown column 'password_confirmation' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:15:16\'
WHERE `usuarios`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:15:16\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:15:16\'
WHERE `usuarios`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 9 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
INFO - 2025-04-21 21:16:22 --> CSRF token verified.
ERROR - 2025-04-21 21:16:22 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\food\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\food\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\food\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\food\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\food\system\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
#8 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\xampp\htdocs\food\system\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
#10 C:\xampp\htdocs\food\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#11 C:\xampp\htdocs\food\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\food\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\food\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\food\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\food\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-04-21 21:16:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: admin/usuarios/atualizar/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 6 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:22\'
WHERE `usuarios`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:22\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 8 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:22 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:22\'
WHERE `usuarios`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:22\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:22\'
WHERE `usuarios`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 9 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
INFO - 2025-04-21 21:16:46 --> CSRF token verified.
ERROR - 2025-04-21 21:16:46 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\food\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\food\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\food\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\food\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\food\system\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
#8 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\xampp\htdocs\food\system\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
#10 C:\xampp\htdocs\food\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#11 C:\xampp\htdocs\food\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\food\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\food\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\food\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\food\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-04-21 21:16:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: admin/usuarios/atualizar/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 6 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:46\'
WHERE `usuarios`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:46\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 8 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:46 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:46\'
WHERE `usuarios`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:46\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:46\'
WHERE `usuarios`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 9 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
INFO - 2025-04-21 21:16:58 --> CSRF token verified.
ERROR - 2025-04-21 21:16:58 --> mysqli_sql_exception: Unknown column 'password' in 'field list' in C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\food\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\food\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\food\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\food\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\food\system\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\food\system\BaseModel.php(1027): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\food\system\Model.php(863): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\food\system\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
#8 C:\xampp\htdocs\food\app\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\xampp\htdocs\food\system\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
#10 C:\xampp\htdocs\food\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
#11 C:\xampp\htdocs\food\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\food\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\food\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\food\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 C:\xampp\htdocs\food\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-04-21 21:16:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
[Method: POST, Route: admin/usuarios/atualizar/1]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 2 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 6 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:58\'
WHERE `usuarios`.`id` IN (\'1\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:58\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 4 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 7 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 8 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
CRITICAL - 2025-04-21 21:16:58 --> [Caused by] mysqli_sql_exception: Unknown column 'password' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:58\'
WHERE `usuarios`.`id` IN (\'1\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:58\'
WHERE `usuarios`.`id` IN (\'1\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `cpf` = \'223.310.598-29\', `telefone` = \'(11) 95149-1707\', `is_admin` = \'1\', `ativo` = \'1\', `password` = \'1234567\', `password_confirmation` = \'1234567\', `updated_at` = \'2025-04-21 21:16:58\'
WHERE `usuarios`.`id` IN (\'1\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `cpf` = :cpf:, `telefone` = :telefone:, `is_admin` = :is_admin:, `ativo` = :ativo:, `password` = :password:, `password_confirmation` = :password_confirmation:, `updated_at` = :updated_at:
WHERE `usuarios`.`id` IN :usuarios.id:', [...], false)
 5 SYSTEMPATH\Model.php(461): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(1027): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(863): CodeIgniter\BaseModel->update([...], [...])
 8 SYSTEMPATH\BaseModel.php(748): CodeIgniter\Model->update('1', Object(App\Entities\Usuario))
 9 APPPATH\Controllers\Admin\Usuarios.php(94): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Usuarios->atualizar('1')
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Usuarios))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\food\\public\\index.php')
